### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by ndrwln** [VincyZed/Sononymefel#1]
Wanted to say this is ingenuity -  leveraging the advantages of sononym and utilizing the advantages of fl studio browser. If FL were keen they would seek to have automatic sample tagging a new feature for smooth integration.

Not many people can do this. This solution might be better than anything that's out there. Plus, one can use XO or ATLAS to audition samples for drums.

**Comment by VincyZed** [comment]
Thanks, indeed having this integrated in the browser would be great, especially since they now have data from FL Cloud that they could use to train a model that could do this. In the meantime, this will do.
Cheers!
